spring.application.name=cweater
spring.datasource.url=jdbc:postgresql://localhost/sweater
spring.datasource.username=postgres
spring.datasource.password=b@se312
spring.jpa.generate-ddl=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.userName=
spring.mail.password=
spring.mail.protocol=smtp
mail.smtp.starttls.enable=true
mail.debug=true


